-- Migration 016: English dish names (name_en)
-- Run in Supabase SQL Editor

UPDATE dishes SET name_en = 'Ajapsandali (Georgian Vegetable Stew)' WHERE name = 'Аджапсандали';
UPDATE dishes SET name_en = 'Avocado Toast' WHERE name = 'Авокадо тост';
UPDATE dishes SET name_en = 'Beef Stroganoff' WHERE name = 'Бефстроганов';
UPDATE dishes SET name_en = 'Beef Bourguignon' WHERE name = 'Бёф Бургиньон';
UPDATE dishes SET name_en = 'Blini (Russian Pancakes)' WHERE name = 'Блины';
UPDATE dishes SET name_en = 'Stuffed Crepes with Meat' WHERE name = 'Блинчики с мясом';
UPDATE dishes SET name_en = 'Borscht' WHERE name = 'Борщ';
UPDATE dishes SET name_en = 'Sausage Sandwiches' WHERE name = 'Бутерброды с колбасой';
UPDATE dishes SET name_en = 'Chicken Burrito' WHERE name = 'Буррито с курицей';
UPDATE dishes SET name_en = 'Potato Dumplings (Varenyky)' WHERE name = 'Вареники с картошкой';
UPDATE dishes SET name_en = 'Potato Dumplings (Varenyky)' WHERE name = 'Вареники с картофелем';
UPDATE dishes SET name_en = 'Boiled Eggs' WHERE name = 'Вареные яйца';
UPDATE dishes SET name_en = 'Gazpacho' WHERE name = 'Газпачо';
UPDATE dishes SET name_en = 'Stuffed Cabbage Rolls' WHERE name = 'Голубцы';
UPDATE dishes SET name_en = 'Meat Stuffed Cabbage Rolls' WHERE name = 'Голубцы с мясом';
UPDATE dishes SET name_en = 'Pea Soup' WHERE name = 'Гороховый суп';
UPDATE dishes SET name_en = 'Pea Soup with Pork' WHERE name = 'Гороховый суп со свининой';
UPDATE dishes SET name_en = 'Egg Croutons' WHERE name = 'Гренки яичные';
UPDATE dishes SET name_en = 'Greek Salad' WHERE name = 'Греческий салат';
UPDATE dishes SET name_en = 'Chinese-Style Beef' WHERE name = 'Говядина по-китайски';
UPDATE dishes SET name_en = 'Beef Goulash' WHERE name = 'Говяжий гуляш';
UPDATE dishes SET name_en = 'Buckwheat with Mushrooms' WHERE name = 'Гречка с грибами';
UPDATE dishes SET name_en = 'Buckwheat with Mushrooms and Onions' WHERE name = 'Гречка с грибами и луком';
UPDATE dishes SET name_en = 'Buckwheat with Boiled Eggs' WHERE name = 'Гречка с вареными яйцами';
UPDATE dishes SET name_en = 'Buckwheat with Chicken' WHERE name = 'Гречка с курицей';
UPDATE dishes SET name_en = 'Buckwheat with Vegetables' WHERE name = 'Гречка с овощами';
UPDATE dishes SET name_en = 'Buckwheat with Fried Eggs' WHERE name = 'Гречка с яичницей';
UPDATE dishes SET name_en = 'Buckwheat with Pork' WHERE name = 'Гречка со свининой';
UPDATE dishes SET name_en = 'Buckwheat Porridge' WHERE name = 'Гречневая каша';
UPDATE dishes SET name_en = 'Buckwheat Porridge with Meat' WHERE name = 'Гречневая каша с мясом';
UPDATE dishes SET name_en = 'Potato Pancakes (Draniki)' WHERE name = 'Драники';
UPDATE dishes SET name_en = 'Fried Potatoes' WHERE name = 'Жареный картофель';
UPDATE dishes SET name_en = 'Fried Rice with Egg' WHERE name = 'Жареный рис с яйцом';
UPDATE dishes SET name_en = 'Chicken and Mushroom Julienne' WHERE name = 'Жульен с курицей и грибами';
UPDATE dishes SET name_en = 'Potato Casserole with Ground Meat' WHERE name = 'Запеканка картофельная с фаршем';
UPDATE dishes SET name_en = 'Potatoes with Boiled Eggs' WHERE name = 'Картофель с вареными яйцами';
UPDATE dishes SET name_en = 'Potatoes with Beef' WHERE name = 'Картофель с говядиной';
UPDATE dishes SET name_en = 'Potatoes with Chicken' WHERE name = 'Картофель с курицей';
UPDATE dishes SET name_en = 'Potatoes with Chicken and Vegetables' WHERE name = 'Картофель с курицей и овощами';
UPDATE dishes SET name_en = 'Potatoes with Vegetables' WHERE name = 'Картофель с овощами';
UPDATE dishes SET name_en = 'Potatoes with Fried Eggs' WHERE name = 'Картофель с яичницей';
UPDATE dishes SET name_en = 'Potato Casserole' WHERE name = 'Картофельная запеканка';
UPDATE dishes SET name_en = 'Mashed Potatoes' WHERE name = 'Картофельное пюре';
UPDATE dishes SET name_en = 'Polish-Style Potatoes with Mushrooms' WHERE name = 'Картошка с грибами по-польски';
UPDATE dishes SET name_en = 'Braised Cabbage with Carrots' WHERE name = 'Капуста тушёная с морковью';
UPDATE dishes SET name_en = 'Cabbage Pie' WHERE name = 'Капустный пирог';
UPDATE dishes SET name_en = 'Chicken Curry' WHERE name = 'Карри с курицей';
UPDATE dishes SET name_en = 'Chicken and Cheese Quesadilla' WHERE name = 'Кесадилья с курицей и сыром';
UPDATE dishes SET name_en = 'Quiche Lorraine' WHERE name = 'Киш Лорен';
UPDATE dishes SET name_en = 'Homemade Meat Patties' WHERE name = 'Котлеты домашние';
UPDATE dishes SET name_en = 'Ground Meat Patties' WHERE name = 'Котлеты из фарша';
UPDATE dishes SET name_en = 'Croque Monsieur' WHERE name = 'Крок-месье';
UPDATE dishes SET name_en = 'Chicken Noodle Soup' WHERE name = 'Куриная лапша';
UPDATE dishes SET name_en = 'Chicken Cutlets' WHERE name = 'Куриные котлеты';
UPDATE dishes SET name_en = 'Chicken Ramen' WHERE name = 'Куриный рамен';
UPDATE dishes SET name_en = 'Chicken Soup' WHERE name = 'Куриный суп';
UPDATE dishes SET name_en = 'Chicken in Sour Cream' WHERE name = 'Курица в сметане';
UPDATE dishes SET name_en = 'Chicken Teriyaki' WHERE name = 'Курица терияки';
UPDATE dishes SET name_en = 'Udon Noodles with Vegetables' WHERE name = 'Лапша удон с овощами';
UPDATE dishes SET name_en = 'Lasagna' WHERE name = 'Лазанья';
UPDATE dishes SET name_en = 'Lobiani (Georgian Bean Bread)' WHERE name = 'Лобиани';
UPDATE dishes SET name_en = 'French Onion Soup' WHERE name = 'Луковый суп по-французски';
UPDATE dishes SET name_en = 'Navy-Style Pasta' WHERE name = 'Макароны по-флотски';
UPDATE dishes SET name_en = 'Pasta with Boiled Eggs' WHERE name = 'Макароны с вареными яйцами';
UPDATE dishes SET name_en = 'Pasta with Beef' WHERE name = 'Макароны с говядиной';
UPDATE dishes SET name_en = 'Pasta with Mushrooms in Sour Cream' WHERE name = 'Макароны с грибами в сметане';
UPDATE dishes SET name_en = 'Pasta with Chicken' WHERE name = 'Макароны с курицей';
UPDATE dishes SET name_en = 'Buttered Pasta' WHERE name = 'Макароны с маслом';
UPDATE dishes SET name_en = 'Pasta with Vegetables' WHERE name = 'Макароны с овощами';
UPDATE dishes SET name_en = 'Pasta with Sausages' WHERE name = 'Макароны с сосисками';
UPDATE dishes SET name_en = 'Pasta with Cheese' WHERE name = 'Макароны с сыром';
UPDATE dishes SET name_en = 'Pasta with Fried Eggs' WHERE name = 'Макароны с яичницей';
UPDATE dishes SET name_en = 'Pasta with Pork' WHERE name = 'Макароны со свининой';
UPDATE dishes SET name_en = 'Semolina Porridge' WHERE name = 'Манная каша';
UPDATE dishes SET name_en = 'Honey Cake (Medovik)' WHERE name = 'Медовик';
UPDATE dishes SET name_en = 'Mexican Bean Soup' WHERE name = 'Мексиканский суп с фасолью';
UPDATE dishes SET name_en = 'Minestrone' WHERE name = 'Минестроне';
UPDATE dishes SET name_en = 'Korean Carrot Salad' WHERE name = 'Морковь по-корейски';
UPDATE dishes SET name_en = 'Gnocchi with Pesto' WHERE name = 'Ньокки с соусом Песто';
UPDATE dishes SET name_en = 'Nachos with Salsa' WHERE name = 'Начос с сальсой';
UPDATE dishes SET name_en = 'Omelette' WHERE name = 'Омлет';
UPDATE dishes SET name_en = 'Mushroom Omelette' WHERE name = 'Омлет с грибами';
UPDATE dishes SET name_en = 'Cheese Omelette' WHERE name = 'Омлет с сыром';
UPDATE dishes SET name_en = 'Cheese and Tomato Omelette' WHERE name = 'Омлет с сыром и помидорами';
UPDATE dishes SET name_en = 'Okroshka (Cold Kefir Soup)' WHERE name = 'Окрошка на кефире';
UPDATE dishes SET name_en = 'Oatmeal with Beef' WHERE name = 'Овсянка с говядиной';
UPDATE dishes SET name_en = 'Oatmeal with Chicken' WHERE name = 'Овсянка с курицей';
UPDATE dishes SET name_en = 'Oatmeal with Pork' WHERE name = 'Овсянка со свининой';
UPDATE dishes SET name_en = 'Oatmeal with Milk' WHERE name = 'Овсяная каша с молоком';
UPDATE dishes SET name_en = 'Chicken Pad Thai' WHERE name = 'Пад Тай с курицей';
UPDATE dishes SET name_en = 'Panna Cotta' WHERE name = 'Панна котта';
UPDATE dishes SET name_en = 'Chicken Paprikash' WHERE name = 'Паприкаш с курицей';
UPDATE dishes SET name_en = 'Pasta Amatriciana' WHERE name = 'Паста Аматричана';
UPDATE dishes SET name_en = 'Pasta Bolognese' WHERE name = 'Паста Болоньезе';
UPDATE dishes SET name_en = 'Pasta Carbonara' WHERE name = 'Паста Карбонара';
UPDATE dishes SET name_en = 'Pasta with Mushrooms in Cream Sauce' WHERE name = 'Паста с грибами в сливочном соусе';
UPDATE dishes SET name_en = 'Seafood Paella' WHERE name = 'Паэлья с морепродуктами';
UPDATE dishes SET name_en = 'Homemade Pelmeni (Russian Dumplings)' WHERE name = 'Пельмени домашние';
UPDATE dishes SET name_en = 'Homemade Pelmeni with Beef' WHERE name = 'Пельмени домашние с говядиной';
UPDATE dishes SET name_en = 'Pizza Margherita' WHERE name = 'Пицца Маргарита';
UPDATE dishes SET name_en = 'Polish Bigos (Hunter''s Stew)' WHERE name = 'Польский бигос';
UPDATE dishes SET name_en = 'Millet Porridge' WHERE name = 'Пшённая каша';
UPDATE dishes SET name_en = 'Vegetable Stew' WHERE name = 'Рагу из овощей';
UPDATE dishes SET name_en = 'Rassolnik (Pickle Soup)' WHERE name = 'Рассольник';
UPDATE dishes SET name_en = 'Fish Pie (Rastegai)' WHERE name = 'Расстегай с рыбой';
UPDATE dishes SET name_en = 'Ratatouille' WHERE name = 'Рататуй по-провансальски';
UPDATE dishes SET name_en = 'Rice with Boiled Eggs' WHERE name = 'Рис с вареными яйцами';
UPDATE dishes SET name_en = 'Rice with Beef' WHERE name = 'Рис с говядиной';
UPDATE dishes SET name_en = 'Rice with Chicken' WHERE name = 'Рис с курицей';
UPDATE dishes SET name_en = 'Rice with Chicken and Vegetables' WHERE name = 'Рис с курицей и овощами';
UPDATE dishes SET name_en = 'Rice with Vegetables' WHERE name = 'Рис с овощами';
UPDATE dishes SET name_en = 'Rice with Fried Eggs' WHERE name = 'Рис с яичницей';
UPDATE dishes SET name_en = 'Rice with Pork' WHERE name = 'Рис со свининой';
UPDATE dishes SET name_en = 'Rice Porridge with Milk' WHERE name = 'Рисовая каша на молоке';
UPDATE dishes SET name_en = 'Mushroom Risotto' WHERE name = 'Ризотто с грибами';
UPDATE dishes SET name_en = 'Fish in Batter' WHERE name = 'Рыба в кляре';
UPDATE dishes SET name_en = 'Baked Fish with Lemon' WHERE name = 'Рыба запечённая с лимоном';
UPDATE dishes SET name_en = 'Chicken Satsivi (Georgian Walnut Sauce)' WHERE name = 'Сациви с курицей';
UPDATE dishes SET name_en = 'Vitamin Salad' WHERE name = 'Салат Верлескоганов';
UPDATE dishes SET name_en = 'Olivier Salad (Russian Potato Salad)' WHERE name = 'Салат Оливье';
UPDATE dishes SET name_en = 'Caesar Salad with Chicken' WHERE name = 'Салат Цезарь с курицей';
UPDATE dishes SET name_en = 'Beet and Garlic Salad' WHERE name = 'Салат из свеклы с чесноком';
UPDATE dishes SET name_en = 'Salmon with Vegetables' WHERE name = 'Семга с овощами';
UPDATE dishes SET name_en = 'Cold Beet Soup' WHERE name = 'Свекольник холодный';
UPDATE dishes SET name_en = 'Sausages with Buckwheat' WHERE name = 'Сосиски с гречкой';
UPDATE dishes SET name_en = 'Sausages with Potatoes' WHERE name = 'Сосиски с картофелем';
UPDATE dishes SET name_en = 'Sausages with Rice' WHERE name = 'Сосиски с рисом';
UPDATE dishes SET name_en = 'Solyanka (Russian Mixed Soup)' WHERE name = 'Солянка';
UPDATE dishes SET name_en = 'Bouillabaisse' WHERE name = 'Суп Буйабес';
UPDATE dishes SET name_en = 'Tom Yum Soup' WHERE name = 'Суп Том Ям';
UPDATE dishes SET name_en = 'Pho Bo (Vietnamese Beef Noodle Soup)' WHERE name = 'Суп Фо бо';
UPDATE dishes SET name_en = 'Mushroom Soup' WHERE name = 'Суп грибной';
UPDATE dishes SET name_en = 'Potato Soup' WHERE name = 'Суп картофельный';
UPDATE dishes SET name_en = 'Kharcho (Georgian Beef and Rice Soup)' WHERE name = 'Суп харчо';
UPDATE dishes SET name_en = 'Vermicelli Soup' WHERE name = 'Суп с вермишелью';
UPDATE dishes SET name_en = 'Lentil Soup' WHERE name = 'Суп из чечевицы';
UPDATE dishes SET name_en = 'Cottage Cheese Pancakes (Syrniki)' WHERE name = 'Сырники';
UPDATE dishes SET name_en = 'Chicken Tagine' WHERE name = 'Тажин с курицей';
UPDATE dishes SET name_en = 'Beef Tacos' WHERE name = 'Тако с говяжьим фаршем';
UPDATE dishes SET name_en = 'Cottage Cheese with Sour Cream' WHERE name = 'Творог со сметаной';
UPDATE dishes SET name_en = 'Cottage Cheese Casserole' WHERE name = 'Творожная запеканка';
UPDATE dishes SET name_en = 'Meatballs in Sauce' WHERE name = 'Тефтели в соусе';
UPDATE dishes SET name_en = 'Meatballs in Sour Cream Sauce' WHERE name = 'Тефтели в сметанном соусе';
UPDATE dishes SET name_en = 'Tiramisu' WHERE name = 'Тирамису';
UPDATE dishes SET name_en = 'Cheese Toast' WHERE name = 'Тосты с сыром';
UPDATE dishes SET name_en = 'Fish Soup (Ukha)' WHERE name = 'Уха';
UPDATE dishes SET name_en = 'Falafel' WHERE name = 'Фалафель';
UPDATE dishes SET name_en = 'Ground Meat with Potatoes' WHERE name = 'Фарш с картофелем';
UPDATE dishes SET name_en = 'Ground Meat with Pasta' WHERE name = 'Фарш с макаронами';
UPDATE dishes SET name_en = 'Beef Fajitas' WHERE name = 'Фахитас с говядиной';
UPDATE dishes SET name_en = 'French Toast' WHERE name = 'Французские тосты';
UPDATE dishes SET name_en = 'Adjarian Khachapuri (Georgian Cheese Bread)' WHERE name = 'Хачапури по-аджарски';
UPDATE dishes SET name_en = 'Meat Khinkali (Georgian Dumplings)' WHERE name = 'Хинкали с мясом';
UPDATE dishes SET name_en = 'Homemade Hummus' WHERE name = 'Хумус домашний';
UPDATE dishes SET name_en = 'Czech Goulash' WHERE name = 'Чешский гуляш';
UPDATE dishes SET name_en = 'Chili con Carne' WHERE name = 'Чили кон карне';
UPDATE dishes SET name_en = 'Chkmeruli (Georgian Garlic Chicken)' WHERE name = 'Чкмерули';
UPDATE dishes SET name_en = 'Eggs Benedict' WHERE name = 'Яйца Бенедикт';
UPDATE dishes SET name_en = 'Fried Eggs' WHERE name = 'Яичница';
UPDATE dishes SET name_en = 'Fried Eggs with Mushrooms' WHERE name = 'Яичница с грибами';
UPDATE dishes SET name_en = 'Fried Eggs with Sausage' WHERE name = 'Яичница с колбасой';
UPDATE dishes SET name_en = 'Fried Eggs with Tomatoes' WHERE name = 'Яичница с помидорами';
UPDATE dishes SET name_en = 'Shchi (Russian Cabbage Soup)' WHERE name = 'Щи из капусты';
UPDATE dishes SET name_en = 'Shakshuka' WHERE name = 'Шакшука';
UPDATE dishes SET name_en = 'Pork Shashlik (BBQ Skewers)' WHERE name = 'Шашлык из свинины';
UPDATE dishes SET name_en = 'New York Cheesecake' WHERE name = 'Чизкейк Нью-Йорк';
UPDATE dishes SET name_en = 'Dolma (Stuffed Grape Leaves)' WHERE name = 'Долма';
