-- Migration 017: Bilingual content — add name_en columns + ingredient translations
-- Run in Supabase SQL Editor

-- Step 1: add bilingual columns
ALTER TABLE dishes ADD COLUMN IF NOT EXISTS name_en TEXT;
ALTER TABLE dishes ADD COLUMN IF NOT EXISTS description_en TEXT;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS name_en TEXT;

-- Step 2: dish name translations (from migration 016 — safe to re-run)
UPDATE dishes SET name_en = 'Ajapsandali (Georgian Vegetable Stew)' WHERE name = 'Аджапсандали';
UPDATE dishes SET name_en = 'Avocado Toast' WHERE name = 'Авокадо тост';
UPDATE dishes SET name_en = 'Beef Stroganoff' WHERE name = 'Бефстроганов';
UPDATE dishes SET name_en = 'Beef Bourguignon' WHERE name = 'Бёф Бургиньон';
UPDATE dishes SET name_en = 'Blini (Russian Pancakes)' WHERE name = 'Блины';
UPDATE dishes SET name_en = 'Stuffed Crepes with Meat' WHERE name = 'Блинчики с мясом';
UPDATE dishes SET name_en = 'Borscht' WHERE name = 'Борщ';
UPDATE dishes SET name_en = 'Sausage Sandwiches' WHERE name = 'Бутерброды с колбасой';
UPDATE dishes SET name_en = 'Chicken Burrito' WHERE name = 'Буррито с курицей';
UPDATE dishes SET name_en = 'Potato Dumplings (Varenyky)' WHERE name = 'Вареники с картошкой';
UPDATE dishes SET name_en = 'Potato Dumplings (Varenyky)' WHERE name = 'Вареники с картофелем';
UPDATE dishes SET name_en = 'Boiled Eggs' WHERE name = 'Вареные яйца';
UPDATE dishes SET name_en = 'Gazpacho' WHERE name = 'Газпачо';
UPDATE dishes SET name_en = 'Stuffed Cabbage Rolls' WHERE name = 'Голубцы';
UPDATE dishes SET name_en = 'Meat Stuffed Cabbage Rolls' WHERE name = 'Голубцы с мясом';
UPDATE dishes SET name_en = 'Pea Soup' WHERE name = 'Гороховый суп';
UPDATE dishes SET name_en = 'Pea Soup with Pork' WHERE name = 'Гороховый суп со свининой';
UPDATE dishes SET name_en = 'Egg Croutons' WHERE name = 'Гренки яичные';
UPDATE dishes SET name_en = 'Greek Salad' WHERE name = 'Греческий салат';
UPDATE dishes SET name_en = 'Chinese-Style Beef' WHERE name = 'Говядина по-китайски';
UPDATE dishes SET name_en = 'Beef Goulash' WHERE name = 'Говяжий гуляш';
UPDATE dishes SET name_en = 'Buckwheat with Mushrooms' WHERE name = 'Гречка с грибами';
UPDATE dishes SET name_en = 'Buckwheat with Mushrooms and Onions' WHERE name = 'Гречка с грибами и луком';
UPDATE dishes SET name_en = 'Buckwheat with Boiled Eggs' WHERE name = 'Гречка с вареными яйцами';
UPDATE dishes SET name_en = 'Buckwheat with Chicken' WHERE name = 'Гречка с курицей';
UPDATE dishes SET name_en = 'Buckwheat with Vegetables' WHERE name = 'Гречка с овощами';
UPDATE dishes SET name_en = 'Buckwheat with Fried Eggs' WHERE name = 'Гречка с яичницей';
UPDATE dishes SET name_en = 'Draniki (Potato Pancakes)' WHERE name = 'Драники';
UPDATE dishes SET name_en = 'Dolma (Stuffed Grape Leaves)' WHERE name = 'Долма';
UPDATE dishes SET name_en = 'Eggs Benedict' WHERE name = 'Яйца Бенедикт';
UPDATE dishes SET name_en = 'Fried Eggs' WHERE name = 'Яичница';
UPDATE dishes SET name_en = 'Fried Eggs with Tomatoes' WHERE name = 'Яичница с помидорами';
UPDATE dishes SET name_en = 'Fried Eggs with Vegetables' WHERE name = 'Яичница с овощами';
UPDATE dishes SET name_en = 'Cottage Cheese with Sour Cream' WHERE name = 'Творог со сметаной';
UPDATE dishes SET name_en = 'Buckwheat Porridge' WHERE name = 'Гречневая каша';
UPDATE dishes SET name_en = 'Chicken Caesar Salad' WHERE name = 'Цезарь с курицей';
UPDATE dishes SET name_en = 'Caesar Salad' WHERE name = 'Цезарь';
UPDATE dishes SET name_en = 'Zucchini Fritters' WHERE name = 'Кабачки жареные';
UPDATE dishes SET name_en = 'Zucchini with Sour Cream' WHERE name = 'Кабачки со сметаной';
UPDATE dishes SET name_en = 'Caprese Salad' WHERE name = 'Капрезе';
UPDATE dishes SET name_en = 'Cabbage Soup (Shchi)' WHERE name = 'Капустные щи';
UPDATE dishes SET name_en = 'Porridge with Cottage Cheese' WHERE name = 'Каша с творогом';
UPDATE dishes SET name_en = 'Millet Porridge' WHERE name = 'Каша из пшена';
UPDATE dishes SET name_en = 'Barley Porridge' WHERE name = 'Каша перловая';
UPDATE dishes SET name_en = 'Semolina Porridge' WHERE name = 'Каша манная';
UPDATE dishes SET name_en = 'Oatmeal Porridge' WHERE name = 'Каша овсяная';
UPDATE dishes SET name_en = 'Pilaf' WHERE name = 'Плов';
UPDATE dishes SET name_en = 'Uzbek Pilaf' WHERE name = 'Плов узбекский';
UPDATE dishes SET name_en = 'Chicken Pilaf' WHERE name = 'Плов с курицей';
UPDATE dishes SET name_en = 'Chicken Kiev' WHERE name = 'Котлета по-киевски';
UPDATE dishes SET name_en = 'Pan-fried Chicken' WHERE name = 'Курица на сковороде';
UPDATE dishes SET name_en = 'Chicken in Cream Sauce' WHERE name = 'Курица в сливочном соусе';
UPDATE dishes SET name_en = 'Baked Chicken' WHERE name = 'Курица запечённая';
UPDATE dishes SET name_en = 'Chicken with Vegetables' WHERE name = 'Курица с овощами';
UPDATE dishes SET name_en = 'Chicken Chkmeruli' WHERE name = 'Чкмерули';
UPDATE dishes SET name_en = 'Fried Potatoes' WHERE name = 'Картошка жареная';
UPDATE dishes SET name_en = 'Baked Potatoes' WHERE name = 'Картошка запечённая';
UPDATE dishes SET name_en = 'Mashed Potatoes' WHERE name = 'Картофельное пюре';
UPDATE dishes SET name_en = 'Mashed Potato Cakes' WHERE name = 'Картофельные зразы';
UPDATE dishes SET name_en = 'Potato Soup' WHERE name = 'Картофельный суп';
UPDATE dishes SET name_en = 'Khinkali (Georgian Dumplings)' WHERE name = 'Хинкали';
UPDATE dishes SET name_en = 'Chicken Khinkali' WHERE name = 'Хинкали с курицей';
UPDATE dishes SET name_en = 'Pelmeni (Russian Dumplings)' WHERE name = 'Пельмени';
UPDATE dishes SET name_en = 'Vegetable Pelmeni' WHERE name = 'Пельмени с овощами';
UPDATE dishes SET name_en = 'Fish Soup (Ukha)' WHERE name = 'Уха';
UPDATE dishes SET name_en = 'Rassolnik Soup' WHERE name = 'Рассольник';
UPDATE dishes SET name_en = 'Solyanka Soup' WHERE name = 'Солянка';
UPDATE dishes SET name_en = 'Borscht with Pork' WHERE name = 'Борщ со свининой';
UPDATE dishes SET name_en = 'Vegetarian Borscht' WHERE name = 'Борщ вегетарианский';
UPDATE dishes SET name_en = 'Shchi (Cabbage Soup)' WHERE name = 'Щи';
UPDATE dishes SET name_en = 'Sour Shchi' WHERE name = 'Щи кислые';
UPDATE dishes SET name_en = 'Mushroom Soup' WHERE name = 'Суп с грибами';
UPDATE dishes SET name_en = 'Cream of Mushroom Soup' WHERE name = 'Суп-пюре из грибов';
UPDATE dishes SET name_en = 'Lentil Soup' WHERE name = 'Суп из чечевицы';
UPDATE dishes SET name_en = 'Vegetable Soup' WHERE name = 'Суп из овощей';
UPDATE dishes SET name_en = 'Bean Soup' WHERE name = 'Суп из фасоли';
UPDATE dishes SET name_en = 'Minestrone' WHERE name = 'Минестроне';
UPDATE dishes SET name_en = 'Tomato Soup' WHERE name = 'Томатный суп';
UPDATE dishes SET name_en = 'Pasta Carbonara' WHERE name = 'Паста карбонара';
UPDATE dishes SET name_en = 'Pasta Bolognese' WHERE name = 'Паста болоньезе';
UPDATE dishes SET name_en = 'Pasta Arrabiata' WHERE name = 'Паста аррабьята';
UPDATE dishes SET name_en = 'Pasta with Pesto' WHERE name = 'Паста с песто';
UPDATE dishes SET name_en = 'Pasta with Mushrooms' WHERE name = 'Паста с грибами';
UPDATE dishes SET name_en = 'Spaghetti' WHERE name = 'Спагетти';
UPDATE dishes SET name_en = 'Spaghetti Carbonara' WHERE name = 'Спагетти карбонара';
UPDATE dishes SET name_en = 'Spaghetti Bolognese' WHERE name = 'Спагетти болоньезе';
UPDATE dishes SET name_en = 'Risotto with Mushrooms' WHERE name = 'Ризотто с грибами';
UPDATE dishes SET name_en = 'Risotto with Seafood' WHERE name = 'Ризотто с морепродуктами';
UPDATE dishes SET name_en = 'Chicken Risotto' WHERE name = 'Ризотто с курицей';
UPDATE dishes SET name_en = 'Lasagna' WHERE name = 'Лазанья';
UPDATE dishes SET name_en = 'Pizza Margherita' WHERE name = 'Пицца Маргарита';
UPDATE dishes SET name_en = 'Shakshuka' WHERE name = 'Шакшука';
UPDATE dishes SET name_en = 'Hummus' WHERE name = 'Хумус';
UPDATE dishes SET name_en = 'Falafel' WHERE name = 'Фалафель';
UPDATE dishes SET name_en = 'Tacos with Chicken' WHERE name = 'Тако с курицей';
UPDATE dishes SET name_en = 'Guacamole' WHERE name = 'Гуакамоле';
UPDATE dishes SET name_en = 'Tom Yum Soup' WHERE name = 'Том ям';
UPDATE dishes SET name_en = 'Ramen' WHERE name = 'Рамен';
UPDATE dishes SET name_en = 'Chicken Ramen' WHERE name = 'Рамен с курицей';
UPDATE dishes SET name_en = 'Pho Bo (Vietnamese Beef Soup)' WHERE name = 'Фо бо';
UPDATE dishes SET name_en = 'Pad Thai' WHERE name = 'Пад Тай';
UPDATE dishes SET name_en = 'Sushi Rolls' WHERE name = 'Суши роллы';
UPDATE dishes SET name_en = 'Paella' WHERE name = 'Паэлья';
UPDATE dishes SET name_en = 'Chicken Paella' WHERE name = 'Паэлья с курицей';
UPDATE dishes SET name_en = 'Seafood Paella' WHERE name = 'Паэлья с морепродуктами';
UPDATE dishes SET name_en = 'Ratatouille' WHERE name = 'Рататуй';
UPDATE dishes SET name_en = 'French Onion Soup' WHERE name = 'Французский луковый суп';
UPDATE dishes SET name_en = 'Quiche Lorraine' WHERE name = 'Киш лорен';
UPDATE dishes SET name_en = 'Crêpes' WHERE name = 'Блины французские';
UPDATE dishes SET name_en = 'New York Cheesecake' WHERE name = 'Чизкейк Нью-Йорк';
UPDATE dishes SET name_en = 'Cheesecake' WHERE name = 'Чизкейк';
UPDATE dishes SET name_en = 'Panna Cotta' WHERE name = 'Панна котта';
UPDATE dishes SET name_en = 'Tiramisu' WHERE name = 'Тирамису';
UPDATE dishes SET name_en = 'Medovik (Honey Cake)' WHERE name = 'Медовик';
UPDATE dishes SET name_en = 'Charlotte (Apple Cake)' WHERE name = 'Шарлотка';
UPDATE dishes SET name_en = 'Oatmeal' WHERE name = 'Овсянка';
UPDATE dishes SET name_en = 'Oatmeal with Fruit' WHERE name = 'Овсянка с фруктами';
UPDATE dishes SET name_en = 'Oatmeal with Honey' WHERE name = 'Овсянка с мёдом';
UPDATE dishes SET name_en = 'Sandwich with Egg' WHERE name = 'Бутерброд с яйцом';
UPDATE dishes SET name_en = 'Sandwich with Cheese' WHERE name = 'Бутерброд с сыром';
UPDATE dishes SET name_en = 'Toast with Avocado' WHERE name = 'Тост с авокадо';
UPDATE dishes SET name_en = 'French Toast' WHERE name = 'Французские тосты';
UPDATE dishes SET name_en = 'Pancakes' WHERE name = 'Панкейки';
UPDATE dishes SET name_en = 'Olivier Salad' WHERE name = 'Оливье';
UPDATE dishes SET name_en = 'Vinegret Salad' WHERE name = 'Винегрет';
UPDATE dishes SET name_en = 'Herring Under a Fur Coat' WHERE name = 'Сельдь под шубой';
UPDATE dishes SET name_en = 'Shashlik (Grilled Skewers)' WHERE name = 'Шашлык';
UPDATE dishes SET name_en = 'Pork Shashlik' WHERE name = 'Шашлык из свинины';
UPDATE dishes SET name_en = 'Manti (Steamed Dumplings)' WHERE name = 'Манты';
UPDATE dishes SET name_en = 'Chicken Cutlets' WHERE name = 'Котлеты из курицы';
UPDATE dishes SET name_en = 'Pork Cutlets' WHERE name = 'Котлеты из свинины';
UPDATE dishes SET name_en = 'Meat Cutlets' WHERE name = 'Котлеты мясные';
UPDATE dishes SET name_en = 'Fish Cutlets' WHERE name = 'Котлеты рыбные';
UPDATE dishes SET name_en = 'Meatballs in Sauce' WHERE name = 'Тефтели в соусе';
UPDATE dishes SET name_en = 'Beef Goulash with Gravy' WHERE name = 'Гуляш с подливкой';
UPDATE dishes SET name_en = 'Pork in Cream Sauce' WHERE name = 'Свинина в сливочном соусе';
UPDATE dishes SET name_en = 'Pork with Vegetables' WHERE name = 'Свинина с овощами';
UPDATE dishes SET name_en = 'Stewed Cabbage' WHERE name = 'Тушёная капуста';
UPDATE dishes SET name_en = 'Stewed Cabbage with Meat' WHERE name = 'Тушёная капуста с мясом';
UPDATE dishes SET name_en = 'Baked Fish' WHERE name = 'Рыба запечённая';
UPDATE dishes SET name_en = 'Fish in Batter' WHERE name = 'Рыба в кляре';
UPDATE dishes SET name_en = 'Salmon Steak' WHERE name = 'Стейк из сёмги';
UPDATE dishes SET name_en = 'Fish with Vegetables' WHERE name = 'Рыба с овощами';
UPDATE dishes SET name_en = 'Stuffed Peppers' WHERE name = 'Фаршированный перец';
UPDATE dishes SET name_en = 'Eggplant Rolls' WHERE name = 'Рулетики из баклажанов';
UPDATE dishes SET name_en = 'Baked Eggplant' WHERE name = 'Баклажаны запечённые';
UPDATE dishes SET name_en = 'Mushrooms with Sour Cream' WHERE name = 'Грибы со сметаной';
UPDATE dishes SET name_en = 'Fried Mushrooms' WHERE name = 'Грибы жареные';
UPDATE dishes SET name_en = 'Tzatziki' WHERE name = 'Дзадзики';
UPDATE dishes SET name_en = 'Pork with Potatoes' WHERE name = 'Картофель со свининой';

-- Step 3: ingredient translations
UPDATE ingredients SET name_en = 'Beef' WHERE name = 'Говядина';
UPDATE ingredients SET name_en = 'Pork' WHERE name = 'Свинина';
UPDATE ingredients SET name_en = 'Chicken' WHERE name = 'Курица';
UPDATE ingredients SET name_en = 'Turkey' WHERE name = 'Индейка';
UPDATE ingredients SET name_en = 'Ground Meat' WHERE name = 'Фарш';
UPDATE ingredients SET name_en = 'Bacon' WHERE name = 'Бекон';
UPDATE ingredients SET name_en = 'Ham' WHERE name = 'Ветчина';
UPDATE ingredients SET name_en = 'Sausage' WHERE name = 'Колбаса';
UPDATE ingredients SET name_en = 'Hot Dogs' WHERE name = 'Сосиски';
UPDATE ingredients SET name_en = 'Pollock' WHERE name = 'Минтай';
UPDATE ingredients SET name_en = 'Salmon' WHERE name = 'Семга';
UPDATE ingredients SET name_en = 'Cod' WHERE name = 'Треска';
UPDATE ingredients SET name_en = 'Tuna' WHERE name = 'Тунец';
UPDATE ingredients SET name_en = 'Shrimp' WHERE name = 'Креветки';
UPDATE ingredients SET name_en = 'Mussels' WHERE name = 'Мидии';
UPDATE ingredients SET name_en = 'Squid' WHERE name = 'Кальмары';

UPDATE ingredients SET name_en = 'Potato' WHERE name = 'Картофель';
UPDATE ingredients SET name_en = 'Carrot' WHERE name = 'Морковь';
UPDATE ingredients SET name_en = 'Onion' WHERE name = 'Лук';
UPDATE ingredients SET name_en = 'Garlic' WHERE name = 'Чеснок';
UPDATE ingredients SET name_en = 'Tomatoes' WHERE name = 'Помидоры';
UPDATE ingredients SET name_en = 'Cucumbers' WHERE name = 'Огурцы';
UPDATE ingredients SET name_en = 'Cabbage' WHERE name = 'Капуста';
UPDATE ingredients SET name_en = 'Broccoli' WHERE name = 'Брокколи';
UPDATE ingredients SET name_en = 'Cauliflower' WHERE name = 'Цветная капуста';
UPDATE ingredients SET name_en = 'Zucchini' WHERE name = 'Кабачки';
UPDATE ingredients SET name_en = 'Eggplant' WHERE name = 'Баклажаны';
UPDATE ingredients SET name_en = 'Bell Pepper' WHERE name = 'Перец болгарский';
UPDATE ingredients SET name_en = 'Chili Pepper' WHERE name = 'Перец чили';
UPDATE ingredients SET name_en = 'Beet' WHERE name = 'Свекла';
UPDATE ingredients SET name_en = 'Spinach' WHERE name = 'Шпинат';
UPDATE ingredients SET name_en = 'Arugula' WHERE name = 'Руккола';
UPDATE ingredients SET name_en = 'Lettuce' WHERE name = 'Листья салата';
UPDATE ingredients SET name_en = 'Celery' WHERE name = 'Сельдерей';
UPDATE ingredients SET name_en = 'Green Onion' WHERE name = 'Лук зеленый';
UPDATE ingredients SET name_en = 'Leek' WHERE name = 'Лук-порей';
UPDATE ingredients SET name_en = 'Radish' WHERE name = 'Редис';
UPDATE ingredients SET name_en = 'Pumpkin' WHERE name = 'Тыква';
UPDATE ingredients SET name_en = 'Asparagus' WHERE name = 'Спаржа';
UPDATE ingredients SET name_en = 'Peas' WHERE name = 'Горошек';
UPDATE ingredients SET name_en = 'Cherry Tomatoes' WHERE name = 'Помидоры черри';
UPDATE ingredients SET name_en = 'Green Beans' WHERE name = 'Стручковая фасоль';
UPDATE ingredients SET name_en = 'Avocado' WHERE name = 'Авокадо';
UPDATE ingredients SET name_en = 'Corn' WHERE name = 'Кукуруза';
UPDATE ingredients SET name_en = 'Mushrooms' WHERE name = 'Грибы';
UPDATE ingredients SET name_en = 'Button Mushrooms' WHERE name = 'Шампиньоны';
UPDATE ingredients SET name_en = 'Oyster Mushrooms' WHERE name = 'Вешенки';
UPDATE ingredients SET name_en = 'Beans' WHERE name = 'Фасоль';
UPDATE ingredients SET name_en = 'Lentils' WHERE name = 'Чечевица';
UPDATE ingredients SET name_en = 'Dried Peas' WHERE name = 'Горох';
UPDATE ingredients SET name_en = 'Chickpeas' WHERE name = 'Нут';
UPDATE ingredients SET name_en = 'Olives' WHERE name = 'Оливки';
UPDATE ingredients SET name_en = 'Canned Peas' WHERE name = 'Консервированный горошек';
UPDATE ingredients SET name_en = 'Canned Beans' WHERE name = 'Консервированная фасоль';

UPDATE ingredients SET name_en = 'Milk' WHERE name = 'Молоко';
UPDATE ingredients SET name_en = 'Kefir' WHERE name = 'Кефир';
UPDATE ingredients SET name_en = 'Sour Cream' WHERE name = 'Сметана';
UPDATE ingredients SET name_en = 'Cottage Cheese' WHERE name = 'Творог';
UPDATE ingredients SET name_en = 'Yogurt' WHERE name = 'Йогурт';
UPDATE ingredients SET name_en = 'Cheese' WHERE name = 'Сыр';
UPDATE ingredients SET name_en = 'Parmesan' WHERE name = 'Пармезан';
UPDATE ingredients SET name_en = 'Mozzarella' WHERE name = 'Моцарелла';
UPDATE ingredients SET name_en = 'Feta' WHERE name = 'Фета';
UPDATE ingredients SET name_en = 'Cream Cheese' WHERE name = 'Творожный сыр';
UPDATE ingredients SET name_en = 'Heavy Cream' WHERE name = 'Сливки';
UPDATE ingredients SET name_en = 'Butter' WHERE name = 'Масло сливочное';

UPDATE ingredients SET name_en = 'Rice' WHERE name = 'Рис';
UPDATE ingredients SET name_en = 'Buckwheat' WHERE name = 'Гречка';
UPDATE ingredients SET name_en = 'Oatmeal' WHERE name = 'Овсянка';
UPDATE ingredients SET name_en = 'Pasta' WHERE name = 'Макароны';
UPDATE ingredients SET name_en = 'Flour' WHERE name = 'Мука';
UPDATE ingredients SET name_en = 'Bread' WHERE name = 'Хлеб';
UPDATE ingredients SET name_en = 'White Loaf' WHERE name = 'Батон';
UPDATE ingredients SET name_en = 'Flatbread (Lavash)' WHERE name = 'Лаваш';
UPDATE ingredients SET name_en = 'Bulgur' WHERE name = 'Булгур';
UPDATE ingredients SET name_en = 'Couscous' WHERE name = 'Кускус';
UPDATE ingredients SET name_en = 'Pearl Barley' WHERE name = 'Перловка';
UPDATE ingredients SET name_en = 'Millet' WHERE name = 'Пшено';
UPDATE ingredients SET name_en = 'Semolina' WHERE name = 'Манная крупа';
UPDATE ingredients SET name_en = 'Breadcrumbs' WHERE name = 'Панировочные сухари';
UPDATE ingredients SET name_en = 'Noodles' WHERE name = 'Лапша';
UPDATE ingredients SET name_en = 'Cookies' WHERE name = 'Печенье';

UPDATE ingredients SET name_en = 'Salt' WHERE name = 'Соль';
UPDATE ingredients SET name_en = 'Black Pepper' WHERE name = 'Перец черный';
UPDATE ingredients SET name_en = 'Paprika' WHERE name = 'Паприка';
UPDATE ingredients SET name_en = 'Turmeric' WHERE name = 'Куркума';
UPDATE ingredients SET name_en = 'Cinnamon' WHERE name = 'Корица';
UPDATE ingredients SET name_en = 'Ginger' WHERE name = 'Имбирь';
UPDATE ingredients SET name_en = 'Cilantro' WHERE name = 'Кинза';
UPDATE ingredients SET name_en = 'Oregano' WHERE name = 'Орегано';
UPDATE ingredients SET name_en = 'Dill' WHERE name = 'Укроп';
UPDATE ingredients SET name_en = 'Parsley' WHERE name = 'Петрушка';
UPDATE ingredients SET name_en = 'Basil' WHERE name = 'Базилик';
UPDATE ingredients SET name_en = 'Nutmeg' WHERE name = 'Мускатный орех';
UPDATE ingredients SET name_en = 'Bay Leaf' WHERE name = 'Лавровый лист';
UPDATE ingredients SET name_en = 'Cumin' WHERE name = 'Кумин';
UPDATE ingredients SET name_en = 'Vanilla' WHERE name = 'Ванилин';
UPDATE ingredients SET name_en = 'Saffron' WHERE name = 'Шафран';
UPDATE ingredients SET name_en = 'Star Anise' WHERE name = 'Бадьян';
UPDATE ingredients SET name_en = 'Cardamom' WHERE name = 'Кардамон';
UPDATE ingredients SET name_en = 'Cloves' WHERE name = 'Гвоздика';

UPDATE ingredients SET name_en = 'Eggs' WHERE name = 'Яйца';
UPDATE ingredients SET name_en = 'Vegetable Oil' WHERE name = 'Масло растительное';
UPDATE ingredients SET name_en = 'Olive Oil' WHERE name = 'Оливковое масло';
UPDATE ingredients SET name_en = 'Tomato Paste' WHERE name = 'Томатная паста';
UPDATE ingredients SET name_en = 'Mayonnaise' WHERE name = 'Майонез';
UPDATE ingredients SET name_en = 'Mustard' WHERE name = 'Горчица';
UPDATE ingredients SET name_en = 'Ketchup' WHERE name = 'Кетчуп';
UPDATE ingredients SET name_en = 'Soy Sauce' WHERE name = 'Соевый соус';
UPDATE ingredients SET name_en = 'Sugar' WHERE name = 'Сахар';
UPDATE ingredients SET name_en = 'Honey' WHERE name = 'Мёд';
UPDATE ingredients SET name_en = 'Vinegar' WHERE name = 'Уксус';
UPDATE ingredients SET name_en = 'Lemon' WHERE name = 'Лимон';
UPDATE ingredients SET name_en = 'Peanuts' WHERE name = 'Арахис';
UPDATE ingredients SET name_en = 'Walnuts' WHERE name = 'Грецкие орехи';
UPDATE ingredients SET name_en = 'Raisins' WHERE name = 'Изюм';
UPDATE ingredients SET name_en = 'Dried Apricots' WHERE name = 'Курага';
UPDATE ingredients SET name_en = 'Tahini' WHERE name = 'Тахини';
UPDATE ingredients SET name_en = 'Sesame' WHERE name = 'Кунжут';
UPDATE ingredients SET name_en = 'Gelatin' WHERE name = 'Желатин';
UPDATE ingredients SET name_en = 'Fish Sauce' WHERE name = 'Рыбный соус';
UPDATE ingredients SET name_en = 'Powdered Sugar' WHERE name = 'Сахарная пудра';
UPDATE ingredients SET name_en = 'Baking Soda' WHERE name = 'Сода';
